### ISSUE TITLE
Connection failed (no connection to the remote host). Internal error: 1. Error details: Code: 2543

### ISSUE THREAD

**Issue by Ablesius** [Azure-Samples/cognitive-services-speech-sdk#1110]
**Describe the bug**
I have followed the code example for transcribing an audio file, and I always get this error:

```
Connection failed (no connection to the remote host). Internal error: 1. Error details: Code: 2543. SessionId: 2caaa438233949fbb5ad24dea9b47a6c
```

**To Reproduce**
1. Create a `speech_config.yml` containing this: 

```yaml 
--- # Azure config
subscription: "add your key from azure here" # key 1 from keys
region: "northeurope"
speech_recognition_language: "de-DE"
```
2. Run the code from here: https://paste.xinu.at/H6tO/

**Expected behavior**
I expected this output:
```
done with recognising. results:
Radio an    # German for "radio on"
```

**Version of the Cognitive Services Speech SDK**
1.17.0

**Platform, Operating System, and Programming Language**
 - OS: Arch Linux (`5.12.6-arch1-1`)
 - Hardware - x86
 - Programming language: Python
 - Browser [e.g. Chrome, Safari] (if applicable) - not applicable
